### ISSUE TITLE
Problems in opening a notebook

### ISSUE THREAD

**Issue by Ali1990dashti** [Japhiolite/gempy-tests#1]
Dear @Japhiolite 
hope doing well and being healthy.
Thank you for your informative notebooks and examples on Gempy.
I had two problems working on them. Firstly, I cannot open the notebook entitled **_GemPy-feature_compilation_** (https://github.com/Japhiolite/gempy-tests/blob/master/notebooks/GemPy-feature_compilation.ipynb). When I try to open it in my browser it say _Sorry, something went wrong_. When I try to load it through Jupyter I see the following error: _Unreadable Notebook: C:\gempy\examples\examples\jan\GemPy-feature_compilation.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')_.
My second issue is related to another example (https://github.com/Japhiolite/gempy-tests/blob/master/notebooks/Test_models.ipynb). In the last example two surfaces (Flat_Series and Inclined_Series) are regarded to act as onlap surfaces on their lower units. I tried this method on your data and my result is different from what you showed as the last picture (output of cell number 218). I draged my result here. Did I make any mistake?
![Zwei_Onlap](https://user-images.githubusercontent.com/62764899/87018203-38978080-c1d1-11ea-8aa4-a58601c4927e.jpeg)

In advance I appreciate any response from your side.

**Comment by Japhiolite** [comment]
Hi @Ali1990dashti 
seems like the first notebook is broken. Will try to fix that.
For the second question: No, your's is right. The `Test_models` notebook was testing some features in an earlier version of GemPy, where onlap-relations had a bug (hence the faulty representation in cell 218). In your version, the bug is solved and onlap-relations are correct.

**Comment by Ali1990dashti** [comment]
Hi @Japhiolite
thank you for the quick response.
I very much look forward to see your informative notebooks and examples.
Cheers,
Ali

**Comment by Japhiolite** [comment]
Notebook should work again now.
